// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOtH3sZuhtSj3ypju-ayJxtl8LDirRuVc',
    appId: '1:400126035855:web:d801aee6ceb17a2734adfa',
    messagingSenderId: '400126035855',
    projectId: 'estiftee-chatbot',
    authDomain: 'estiftee-chatbot.firebaseapp.com',
    storageBucket: 'estiftee-chatbot.firebasestorage.app',
    measurementId: 'G-RN23FGQ1Q3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWU9PwG0XCXZBYGZT5mOLocsgTLUQIao8',
    appId: '1:400126035855:android:1702c662419ed96334adfa',
    messagingSenderId: '400126035855',
    projectId: 'estiftee-chatbot',
    storageBucket: 'estiftee-chatbot.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVa6L4R39v7xvHVv-YjxD1rN1-z3fJ-ZU',
    appId: '1:400126035855:ios:c01f5d7e832ae92434adfa',
    messagingSenderId: '400126035855',
    projectId: 'estiftee-chatbot',
    storageBucket: 'estiftee-chatbot.firebasestorage.app',
    iosBundleId: 'com.example.estifteeChatbot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVa6L4R39v7xvHVv-YjxD1rN1-z3fJ-ZU',
    appId: '1:400126035855:ios:c01f5d7e832ae92434adfa',
    messagingSenderId: '400126035855',
    projectId: 'estiftee-chatbot',
    storageBucket: 'estiftee-chatbot.firebasestorage.app',
    iosBundleId: 'com.example.estifteeChatbot',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOtH3sZuhtSj3ypju-ayJxtl8LDirRuVc',
    appId: '1:400126035855:web:55807ea80d05564c34adfa',
    messagingSenderId: '400126035855',
    projectId: 'estiftee-chatbot',
    authDomain: 'estiftee-chatbot.firebaseapp.com',
    storageBucket: 'estiftee-chatbot.firebasestorage.app',
    measurementId: 'G-Q9V3NY20QQ',
  );
}
